Update typescript and enable support for optional chaining
Update typescript and install @babel/plugin-proposal-optional-chaining. Also
explicitly update @typescript-eslint/parser as dev dependency to avoid getting
error: You are currently running a version of TypeScript which is not officially
supported by typescript-estree.
This explicit dev dependency can be removed in the future.